### ISSUE TITLE
Build failure for i686-unknown-hurd-gnu

### ISSUE THREAD

**Issue by asomers** [bytecodealliance/rustix#1007]
With the latest libc dependency, the build fails for i686-unknown-hurd-gnu
```
> cargo check -Zbuild-std --target i686-unknown-hurd-gnu --features="fs"
   Compiling rustix v0.38.31 (/usr/home/somers/src/rust/rustix)
error[E0609]: no field `st_atime` on type `&libc::stat64`
   --> src/fs/mod.rs:168:14
    |
168 |         self.st_atime as i64
    |              ^^^^^^^^ unknown field
    |
help: a field with a similar name exists
    |
168 |         self.st_atim as i64
    |              ~~~~~~~

error[E0609]: no field `st_mtime` on type `&libc::stat64`
   --> src/fs/mod.rs:172:14
    |
172 |         self.st_mtime as i64
    |              ^^^^^^^^ unknown field
    |
help: a field with a similar name exists
    |
172 |         self.st_mtim as i64
    |              ~~~~~~~

error[E0609]: no field `st_ctime` on type `&libc::stat64`
   --> src/fs/mod.rs:176:14
    |
176 |         self.st_ctime as i64
    |              ^^^^^^^^ unknown field
    |
help: a field with a similar name exists
    |
176 |         self.st_ctim as i64
    |              ~~~~~~~

For more information about this error, try `rustc --explain E0609`.
error: could not compile `rustix` (lib) due to 3 previous errors
```

**Comment by SteveLauC** [comment]
For rustix, I got different errors:

```sh
$ cargo +nightly --version
cargo 1.78.0-nightly (cdf84b69d 2024-02-02)

$ cargo +nightly check -Zbuild-std --target i686-unknown-hurd-gnu --all-features --all-targets
   Compiling serial_test_derive v2.0.0
    Checking compiler_builtins v0.1.108
    Checking errno v0.3.8
    Checking futures-util v0.3.30
    Checking parking_lot_core v0.9.9
    Checking flate2 v1.0.28
    Checking memoffset v0.9.0
error[E0433]: failed to resolve: could not find `prelude` in `core`

error[E0432]: unresolved import `core::ops`
 --> /home/steve/.cargo/registry/src/index.crates.io-6f17d22bba15001f/compiler_builtins-0.1.108/src/float/mod.rs:1:5
  |
1 | use core::ops;
  |     ^^^^^^^^^ no `ops` in the root

error[E0432]: unresolved import `core::ops`
 --> /home/steve/.cargo/registry/src/index.crates.io-6f17d22bba15001f/compiler_builtins-0.1.108/src/int/mod.rs:1:5
  |
1 | use core::ops;
  |     ^^^^^^^^^ no `ops` in the root

error[E0432]: unresolved import `core::intrinsics`
  --> /home/steve/.cargo/registry/src/index.crates.io-6f17d22bba15001f/compiler_builtins-0.1.108/src/mem/mod.rs:11:11
   |
11 | use core::intrinsics::{atomic_load_unordered, atomic_store_unordered, exact_div};
   |           ^^^^^^^^^^ could not find `intrinsics` in `core`

```

**Comment by SteveLauC** [comment]
Well, I just realized that the error reported by @asomers comes from [this CI log](https://github.com/nix-rust/nix/actions/runs/7775039226/job/21200536201?pr=2269), and we should note that rustix 0.38.31 is using libc 0.2.152, which is not the latest version (0.2.153, released on 2/1/2024)

**Comment by sunfishcode** [comment]
As of #1064 and #1066, `cargo +nightly check -Zbuild-std --target i686-unknown-hurd-gnu --features="fs"` now builds successfully.

**Comment by williamdes** [comment]
I have something similar on `loongarch64`

```
error[E0609]: no field `st_atime` on type `&libc::stat`
   --> /builds/williamdes/aports/community/horust/tmp/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rustix-0.38.44/src/fs/mod.rs:173:14
    |
173 |         self.st_atime as i64
    |              ^^^^^^^^ unknown field
    |
help: a field with a similar name exists
    |
173 -         self.st_atime as i64
173 +         self.st_atim as i64
    |
error[E0609]: no field `st_mtime` on type `&libc::stat`
   --> /builds/williamdes/aports/community/horust/tmp/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rustix-0.38.44/src/fs/mod.rs:178:14
    |
178 |         self.st_mtime as i64
    |              ^^^^^^^^ unknown field
    |
help: a field with a similar name exists
    |
178 -         self.st_mtime as i64
178 +         self.st_mtim as i64
    |
error[E0609]: no field `st_ctime` on type `&libc::stat`
   --> /builds/williamdes/aports/community/horust/tmp/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rustix-0.38.44/src/fs/mod.rs:183:14
    |
183 |         self.st_ctime as i64
    |              ^^^^^^^^ unknown field
    |
help: a field with a similar name exists
    |
183 -         self.st_ctime as i64
183 +         self.st_ctim as i64
    |
```
https://gitlab.alpinelinux.org/williamdes/aports/-/jobs/2243110

**Comment by huajingyun01** [comment]
> I have something similar on `loongarch64`
> 
> ```
> error[E0609]: no field `st_atime` on type `&libc::stat`
>    --> /builds/williamdes/aports/community/horust/tmp/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rustix-0.38.44/src/fs/mod.rs:173:14
>     |
> 173 |         self.st_atime as i64
>     |              ^^^^^^^^ unknown field
>     |
> help: a field with a similar name exists
>     |
> 173 -         self.st_atime as i64
> 173 +         self.st_atim as i64
>     |
> error[E0609]: no field `st_mtime` on type `&libc::stat`
>    --> /builds/williamdes/aports/community/horust/tmp/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rustix-0.38.44/src/fs/mod.rs:178:14
>     |
> 178 |         self.st_mtime as i64
>     |              ^^^^^^^^ unknown field
>     |
> help: a field with a similar name exists
>     |
> 178 -         self.st_mtime as i64
> 178 +         self.st_mtim as i64
>     |
> error[E0609]: no field `st_ctime` on type `&libc::stat`
>    --> /builds/williamdes/aports/community/horust/tmp/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rustix-0.38.44/src/fs/mod.rs:183:14
>     |
> 183 |         self.st_ctime as i64
>     |              ^^^^^^^^ unknown field
>     |
> help: a field with a similar name exists
>     |
> 183 -         self.st_ctime as i64
> 183 +         self.st_ctim as i64
>     |
> ```
> 
> https://gitlab.alpinelinux.org/williamdes/aports/-/jobs/2243110

For loongarch64, this is a known [issue](https://github.com/rust-lang/libc/issues/4939) upstream in libc, which has been [fixed](https://github.com/rust-lang/libc/pull/4958) since [libc 0.2.181](https://github.com/rust-lang/libc/releases/tag/0.2.181).
