### ISSUE TITLE
Thoughts on higher level APIs?

### ISSUE THREAD

**Issue by SUPERCILEX** [bytecodealliance/rustix#1016]
I'm thinking about adding `copy_file_range_all` which does the looping until EOF. I'd also like a `link_tmp_file` which does an allocation free linkat to the right `/proc` fd. Thoughts on adding these? I already have the implementations, I'm just wondering if it makes sense to upstream them.

**Comment by notgull** [comment]
I believe that the stance is that higher level APIs belong in other crates, like with [`rustix-openpty`](https://docs.rs/rustix-openpty/latest/rustix_openpty/).

**Comment by notgull** [comment]
I believe that the stance is that higher level APIs belong in other crates, like with [`rustix-openpty`](https://docs.rs/rustix-openpty/latest/rustix_openpty/).

**Comment by sunfishcode** [comment]
Yes, these sound like things that can be implemented in terms of rustix's public API, so we should ideally put them in a separate crate.

**Comment by SUPERCILEX** [comment]
Ok, thanks!
