### ISSUE TITLE
Start work on rustix 1.0

### ISSUE THREAD

**Issue by morr0ne** [bytecodealliance/rustix#1030]
Rustix has been on version 0.38.x for a while and work towards a 1.0 release seems to be a bit stale. There is already a 1.0 issue here #753 but it does not seem like any work has actually started. I feel like rustix should begin moving forward and start working on a 1.0 release.

Ideally the following things would happen
- The current main branch would start accepting breaking changes
- Create a new 0.38 branch based on the current main to keep supporting that version
- Start releasing "release candidates" for the 1.0 version on crates.io

The work required for a 1.0 release is quite lengthy has highlighted in #753, this would allow to start working on some of it.

I am aware the a `1.0-staging` branch already exists but it currently only houses 2 commits which could be easily pulled into the main branch

Finally it would probably help adding a corresponding project and issue label to better track the changes

**Comment by notgull** [comment]
+1 to this. I'd like to start working on removing the last appearances of `linux-raw-sys` in the public API.

**Comment by sunfishcode** [comment]
My rough idea right now is to finish up #1118 (or figure out an alternative) and anything else ready to go in that time, and then do a 0.38.35 release. If there's anything I'm missing that would be good to get into 0.38.35, please do ping. Once that's out, create a 0.38 maintenance branch, merge 1.0-staging into main, and main can target the eventual 1.0 release.
