### ISSUE TITLE
regression in rustix 0.38.33+ on i686-unknown-linux-gnu

### ISSUE THREAD

**Issue by decathorpe** [bytecodealliance/rustix#1052]
I started seeing build failures of at least to crates (async-process, polling) after I updated the Fedora Linux package for rustix from v0.38.31 to v0.38.33.

The crashes in the async-process and polling crates' test suites originate at an `Option::unwrap()` in rustix code:

```
thread 'test::polled_driver' panicked at /usr/share/cargo/registry/rustix-0.38.33/src/backend/linux_raw/param/auxv.rs:298:68:
called `Option::unwrap()` on a `None` value
```

see also my original report against `polling`: https://github.com/smol-rs/polling/issues/200

---

EDIT: I now realize that this change could also have been introduced in rustix v0.38.32, but we skipped that version in Fedora, so I can't say for sure.

**Comment by decathorpe** [comment]
I'm now also seeing similar failures in timerfd v1.6.0 on x86_64, with a None-unwrap at the same location in rustix, so I'm not sure if this is even specific to i686-unknown-linux-gnu.

**Comment by sunfishcode** [comment]
Thanks for the report! This is fixed in rustix 0.38.34.

The regression was introduced in rustix 0.38.33, which I've now yanked.

**Comment by decathorpe** [comment]
Thanks! Sorry that I didn't check 0.38.34 specifically - the only change I saw was https://github.com/bytecodealliance/rustix/pull/1049 and it didn't sound relevant at all.

**Comment by sunfishcode** [comment]
What happened was, #1049 has what I thought was a simple fix for a compiler warning, but later discovered actually fixes this bug.

**Comment by decathorpe** [comment]
Can confirm that 0.38.34 fixes the issue. The polling, async-process, and timerfd crates' test suites pass again. Thank you!
