### ISSUE TITLE
`SendFlags::EOT` seems to be misspelled

### ISSUE THREAD

**Issue by KarsMulder** [bytecodealliance/rustix#1053]
`SendFlags::EOT` is currently [defined](https://github.com/bytecodealliance/rustix/blob/14a88ef008f2e69e10aa31b75dc191b07b412bca/src/backend/linux_raw/net/send_recv.rs#L20) as:

```
/// `MSG_EOT`
const EOT = c::MSG_EOR;
```

I.e. the flag that appears to be called `MSG_EOT` actually compiles to `MSG_EOR`. Indeed, `MSG_EOR` is the correct name of this send flag according to the [man page](https://linux.die.net/man/2/sendmsg); a flag called called `MSG_EOT` doesn't actually exist in Linux as far as I can tell.

I propose that `SendFlags::EOT` gets renamed to `SendFlags::EOR`. This, of course, is a breaking API change.

**Comment by sunfishcode** [comment]
Renaming it would be breaking, but we can add the new name and deprecate the old one without a breaking change. I've now opened #1054 to do that.
