### ISSUE TITLE
tcsetwinsize should use &Winsize

### ISSUE THREAD

**Issue by tianyuanhao** [bytecodealliance/rustix#1083]
🤔 _I find that only references to `Winsize` are used in the implementation._

Refs: #671, #673

✨ I've understood. It's because `Winsize` is too small, so it's OK to pass the value directly, right?

**Comment by sunfishcode** [comment]
I believe either way works and that it's just a question of API convenience and perhaps low-level optimization. I think the original idea was that passing it by value would be more convenient, but I'd be interested in hearing how it works out in practice.
