### ISSUE TITLE
1.0-staging was rebased incorrectly

### ISSUE THREAD

**Issue by SUPERCILEX** [bytecodealliance/rustix#1107]
@sunfishcode it looks like two 1.0 PRs were wiped off the map accidentally. https://github.com/bytecodealliance/rustix/pull/996 and https://github.com/bytecodealliance/rustix/pull/1063 don't exist anymore.

1.0 PRs: https://github.com/bytecodealliance/rustix/pulls?q=is%3Apr+base%3A1.0-staging+is%3Aclosed

**Comment by sunfishcode** [comment]
Oops, thanks for catching that. I've now cherry-picked those patches back into the 1.0-staging tree.

**Comment by SUPERCILEX** [comment]
Sweet!
