### ISSUE TITLE
fs: using -EBADF as a dirfd argument

### ISSUE THREAD

**Issue by cyphar** [bytecodealliance/rustix#1187]
Some programs want to ensure that no paths are resolved relative to the current directory, and so use `-EBADF` as a file descriptor argument so that an error is returned if the path is not absolute. [This is a fairly common pattern](https://github.com/search?q=at%28-EBADF&type=code), but unfortunately rustix does not allow it:

```
thread 'utils::fd::tests::metadata_badfd' panicked at /home/cyphar/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustix-0.38.37/src/backend/linux_raw/conv.rs:165:5:
assertion failed: fd == crate::fs::CWD.as_raw_fd() || fd >= 0
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

The one-line patch for this is fairly straightforward (only disallow `-1` since that's an invalid `BorrowedFd` value) but I wanted to make sure that there wasn't a nicer solution (maybe we should just define a new `CWD`-like constant akin to `no_fd` so users can just re-use that).

**Comment by sunfishcode** [comment]
Interesting, I hadn't heard of that convention before. I think defining a new `CWD`-like constant sounds good. I've now posted https://github.com/bytecodealliance/rustix/pull/1189 with a path for this.
