### ISSUE TITLE
Changing `xdp_umem_reg` definition

### ISSUE THREAD

**Issue by tgross35** [bytecodealliance/rustix#1221]
Linux 6.12 added a new field to `xdp_umem_reg`, `tx_metadata_len` ([patch](https://github.com/torvalds/linux/commit/341ac980eab90ac1f6c22ee9f9da83ed9604d899)). We have a PR to add this field to `libc` at https://github.com/rust-lang/libc/pull/3956, and based on an [informal search](https://github.com/search?q=%2Fxdp_umem_reg%2F+lang%3Arust+%28NOT+path%3Axdp.rs%29+%28NOT+path%3Alinux_like%2Flinux%29&type=code&p=1) it seems like `rustix` might be about the only crate making use of this type currently. Is there any way we could add this field to `libc` without breaking things for `rustix`?

Considering this is a break in uapi I think we probably have some leeway making a breaking change on our end too, but I want to be sure it won't cause a build failure for everyone using `rustix`.

**Comment by arctic-alpaca** [comment]
For some added context, https://github.com/bytecodealliance/rustix/pull/1061 is currently blocked on the update of `xdp_umem_reg` in `libc`.

**Comment by sunfishcode** [comment]
From looking at the code, it doesn't look like anything will break for rustix's users if libc makes that change. Rustix doesn't use `xdp_umem_reg` directly for anything; it have its own `XdpUmemReg`. And the only thing rustix does with it is pass it to `setsockopt`, where a pointer and length are passed, so the kernel will only fill in the fields that rustix is expecting.

**Comment by tgross35** [comment]
Thanks for confirming! Guess we are all set then, the update should be in the next release.
