### ISSUE TITLE
Compiler error on rustix.

### ISSUE THREAD

**Issue by limuyao1996** [bytecodealliance/rustix#1224]
I use some packages that  depend on rustix. Then I got a compiler error on rustix@0.38.41. Is this a code error in rustix?

My env:
rustc 1.82.0 (f6e511eec 2024-10-15)
cargo 1.82.0 (8f40fc59f 2024-08-21)
Macbook pro M1 pro

```bash
Compiling rustix v0.38.41
error[E0015]: cannot call non-const fn `libc::CMSG_SPACE` in constant functions
   --> /Users/limuyao/.cargo/registry/src/rsproxy.cn-0dccff568467c15b/rustix-0.38.41/src/net/send_recv/msg.rs:120:14
    |
120 |     unsafe { c::CMSG_SPACE(converted_len) as usize }
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: calls in constant functions are limited to constant functions, tuple structs and tuple variants

For more information about this error, try `rustc --explain E0015`.
error: could not compile `rustix` (lib) due to 1 previous error
```

**Comment by limuyao1996** [comment]
> I don't know; I'm not able to reproduce this. Are you cross-compiling here, and if so, to what target? What version of the libc crate is in use here?

Thank you for your reply.
Thanks to your reminder, I checked the issues in the libc repository and found that this seems to be an issue with libc.
This's the link to the related issue: https://github.com/rust-lang/libc/issues/4115

**Comment by sunfishcode** [comment]
Thanks for posting the link to that libc issue. I'll close this issue, as this isn't a rustix issue.
