### ISSUE TITLE
Why is `fs::Dir` not `Sync`?

### ISSUE THREAD

**Issue by nrath-js** [bytecodealliance/rustix#1230]
I was surprised to see that the `fs::Dir` type is not marked as `Sync`.

As far as I can tell, all methods that access the internal state require a `&mut self`, so I think it's fine to use this type from multiple threads without the need for another mutex (since at most one thread can hold a `&mut` reference).

Am I missing something?

**Comment by sunfishcode** [comment]
I think you're right; it could be `Sync`.

**Comment by notgull** [comment]
It is `Sync` on the linux_raw backend, but not the libc one.
