### ISSUE TITLE
cannot find macro `asm` in this scope

### ISSUE THREAD

**Issue by nazar-pc** [bytecodealliance/rustix#142]
Getting these CI errors in latest nightly:
```
error: cannot find macro `asm` in this scope
  --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/rsix-0.23.9/src/imp/linux_raw/arch/inline/x86_64.rs:57:5
   |
57 |     asm!(
   |     ^^^
   |
   = note: consider importing one of these items:
           std::arch::asm
           core::arch::asm
```

Example CI run: https://github.com/subspace/subspace/runs/4541885325?check_suite_focus=true

**Comment by sunfishcode** [comment]
Thanks for the report! This is fixed on main in #143. I'll publish a new rustix release soon, and then a Wasmtime PR to update to it. After that, it'll be in the [following Wasmtime release](https://docs.wasmtime.dev/contributing-release-process.html).

**Comment by nazar-pc** [comment]
Thank you for quick reaction!

**Comment by nazar-pc** [comment]
Does this qualify for a patch release?

**Comment by sunfishcode** [comment]
I don't think so, since it isn't a security problem, and it only affects the very latest Rust nightlies. A workaround is to temporarily pin to a Rust nightly version from a few days ago; I'd be happy to help you set this up if that would help. Also, as an update to the above, I've now made the PR to update Wasmtime, and it has now landed, so it'll be in the next regular Wasmtime release.

**Comment by nazar-pc** [comment]
I have already pinned Rust nightly of course, but as many projects use latest nightly in CI, this issue is quite annoying and next wasmtime release will only be in a month, so I was hoping patch release can be issued sooner.

**Comment by sunfishcode** [comment]
I recognize it's inconvenient. I volunteer to do the work to set up the workaround for any project which encounters this; just let me know in a message here.

**Comment by eminence** [comment]
For anyone following along at home, you need `nightly-2021-12-15` or older
