### ISSUE TITLE
[Q&A] Are smaller program startup times possible if `libc` isn't used?

### ISSUE THREAD

**Issue by Byron** [bytecodealliance/rustix#156]
Having recently read [this article](http://ryanhileman.info/posts/lib43) that describes how the launch time of a C program could be reduced to 1ms from 10ms I thought that maybe with `rustix + origin`, it would be possible to emit more optimal program startup sequences based on the actual usage of features in the program.

Is this achievable or is there a good reason for libc based programs not to typically do that?

Thanks

**Comment by sunfishcode** [comment]
In programs that use libc, it's necessary to use libc's startup code. C effectively has a runtime, and it needs to be initialized before any C functions can be called. And the only way the C runtime provides users to do that is to let it start up and be in charge of the process. Rustix is designed to coexist with whatever it happens to share a process with, including libc.

[Origin](https://github.com/sunfishcode/mustang/tree/main/origin) is a related crate which *is* in the business of process startup. With origin in mustang, a strace of hello world looks like this:

```
execve("target/x86_64-mustang-linux-gnu/release/examples/hello", ["target/x86_64-mustang-linux-gnu/"...], 0x7fffa142f6f0 /* 50 vars */) = 0
prlimit64(0, RLIMIT_STACK, NULL, {rlim_cur=8192*1024, rlim_max=RLIM64_INFINITY}) = 0
mmap(NULL, 296, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f71fec5b000
gettid()                                = 80011
arch_prctl(ARCH_SET_FS, 0x7f71fec5b098) = 0
madvise(0x7ffc66fe1000, 64, MADV_NORMAL) = 0
clock_getres(CLOCK_MONOTONIC, 0x7ffc66fe1000) = -1 EFAULT (Bad address)
mmap(NULL, 65536, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f71fec4b000
poll([{fd=0, events=0}, {fd=1, events=0}, {fd=2, events=0}], 3, 0) = 0 (Timeout)
write(1, "Hello, world!\n", 14Hello, world!
)         = 14
exit_group(0)                           = ?
```

After the `execve`, the first few syscalls are origin setting up the main thread. This could probably be skipped if we know the program only has one thread. The `madvise` and `clock_getres` are rustix testing whether the vDSO image it found in memory is legit; there may be ways to optimize those. The next `mmap` is parking_lot doing an allocation for its global state, which could also be avoided in some situations (such as not needing threads). The next `poll` is Rust ensuring that file descriptors 0, 1, and 2 exist.

Then the `write` says hello, and `exit_group` ends the process. So it's pretty frugal overall, but there are a few opportunities to optimize things.

**Comment by Byron** [comment]
Thanks a lot for the detailed response!

To me that sounds like all kinds of optimizations are possible _once_ libc isn't used anymore in favor of a pure Rust implementation. Even though by the nature of statically bundling portions of the rust-std with each Rust binary each of these is relatively large by default unless disabled entirely, one might still get sub-10ms launch times if the process bootstrapping code is optimized. That way Rust binaries would have another advantage over C.
