### ISSUE TITLE
`utimensat` not available on all macOS versions

### ISSUE THREAD

**Issue by ggreif** [bytecodealliance/rustix#157]
I have an update in the works for `wasmtime` to a recent version in `nixpkgs`. We are seeing build failures because the macOS link context of `nixpkgs` doesn't support `utimensat`:
https://github.com/NixOS/nixpkgs/pull/109571#issuecomment-923693874, also see https://github.com/NixOS/nixpkgs/pull/109571/checks?check_run_id=4551627548.

I looked at the [Darwin implementation](https://github.com/apple/darwin-xnu/blob/main/libsyscall/wrappers/utimensat.c), and it looks like a candidate for a Rust port (and to be used when the OS doesn't provide it).

**Comment by BenStruhl** [comment]
I think I can work on writing a native implementation of this. Would I write said function here https://github.com/bytecodealliance/rustix/blob/main/src/imp/libc/fs/syscalls.rs and have it only compile on macOS?

**Comment by BenStruhl** [comment]
also would libc's  setattrlistat be able to be used or no ?

**Comment by sunfishcode** [comment]
@BenStruhl I'm curious if you've had a chance to look at this, and if so, what you've learned.
