### ISSUE TITLE
the api exports constant from bits, can we reverse it?

### ISSUE THREAD

**Issue by lygstate** [bytecodealliance/rustix#173]

**Comment by sunfishcode** [comment]
Could I ask you to clarify which constants you're referring to, and what reversing them would mean?

**Comment by lygstate** [comment]
For example:

https://github.com/bytecodealliance/rustix/commit/9608e75f4e966943a092ae3995d82d3fbe45b797#diff-c61194c4c7b5fe774c64aa2d5bc9e113512c33459b7820d03f70b365b1051595R75

**Comment by sunfishcode** [comment]
What would reversing them mean?

**Comment by sunfishcode** [comment]
Could you perhaps post an example of the kind of change you'd like to see here?
