### ISSUE TITLE
Compile Android arm64 libwasmtime.a  happens link error?

### ISSUE THREAD

**Issue by LukiYLS** [bytecodealliance/rustix#256]
/Users/lukiyang/Work/sourcecode/DynamicFramework/core/third_party/wasmtime/lib/android/arm64-v8a/libwasmtime.a(rustix-7ff7823763dd1c95.rustix.57691c6b-cgu.7.rcgu.o): In function `rustix::imp::io::syscalls::preadv::h9ff81e210c739d18':
  /Users/lukiyang/.cargo/registry/src/github.com-1ecc6299db9ec823/rustix-0.33.0/src/imp/libc/io/syscalls.rs:122: undefined reference to `preadv64'
  /Users/lukiyang/Work/sourcecode/DynamicFramework/core/third_party/wasmtime/lib/android/arm64-v8a/libwasmtime.a(rustix-7ff7823763dd1c95.rustix.57691c6b-cgu.7.rcgu.o): In function `rustix::imp::io::syscalls::pwritev::hb6ef9b4b3c378517':
  /Users/lukiyang/.cargo/registry/src/github.com-1ecc6299db9ec823/rustix-0.33.0/src/imp/libc/io/syscalls.rs:137: undefined reference to `pwritev64'

**Comment by sunfishcode** [comment]
Thanks for the report! I submitted #256 which hopefully fixes these. I unfortunately don't have Android systems to test these on, so please file further issues if there are any further problems after this.

**Comment by LukiYLS** [comment]
> Thanks for the report! I submitted #256 which hopefully fixes these. I unfortunately don't have Android systems to test these on, so please file further issues if there are any further problems after this.

Cherry-pick to 0.33.0 has compile error

error[E0432]: unresolved imports `super::super::offset::libc_preadv`, `super::super::offset::libc_pwritev`
  --> /Users/lukiyang/.cargo/registry/src/github.com-1ecc6299db9ec823/rustix-0.33.0/src/imp/libc/io/syscalls.rs:13:28
   |
13 | use super::super::offset::{libc_preadv, libc_pwritev};
   |                            ^^^^^^^^^^^  ^^^^^^^^^^^^ no `libc_pwritev` in `imp::offset`
   |                            |
   |                            no `libc_preadv` in `imp::offset`
   |
help: a similar name exists in the module
   |
13 | use super::super::offset::{libc_pread, libc_pwritev};
   |                            ~~~~~~~~~~
help: a similar name exists in the module
   |
13 | use super::super::offset::{libc_preadv, libc_pwrite};
   |                                         ~~~~~~~~~~~

**Comment by LukiYLS** [comment]
> Thanks for the report! I submitted #258 which hopefully fixes these. I unfortunately don't have Android systems to test these on, so please file further issues if there are any further problems after this.

I use android verify OK

**Comment by sunfishcode** [comment]
> > Thanks for the report! I submitted #258 which hopefully fixes these. I unfortunately don't have Android systems to test these on, so please file further issues if there are any further problems after this.
> 
> I use android verify OK

Thanks! I'm [preparing](https://github.com/bytecodealliance/rustix/pull/262) a 0.33.5 point release so that we can get the fix into Wasmtime.
