### ISSUE TITLE
support: I misunderstand something about a borrowed `OwnedFd` and drop.

### ISSUE THREAD

**Issue by cheako** [bytecodealliance/rustix#257]
I'm working on examples a little more advanced than basic.  I'd like to see other examples of this.  I'm wanting to `socat` a command with a socket.

https://gitlab.com/cheako/rust-general/-/blob/0a352884935086da7e82e1866be56efd8d855a0a/agis_phiwraek/src/lib.rs#L59-100

The unix socket gets closed, causing the write to fail, and I don't understand why.  Could be something to-do with `try_clone()`?  Also, the program gets into a state where the listening socket is closed but two places it should panic never fire.

**Comment by sunfishcode** [comment]
The `go` doc test in that code passes for me. Could you say more about the problem you're seeing?

**Comment by cheako** [comment]
The doc test sleeps and during that sleep I'm running `nc /tmp/b` and typing a line.  This closes the socket, when it should panic in two places.  I'd rather it joined the socket connection to a running program.

**Comment by cheako** [comment]
I fixed up the function so now I at least get the panic.  Still don't understand why FDs are being closed, the OwnedFd are still clearly borrowed.

```
/// ```
/// #![feature(duration_constants)]
///
/// use thread_tryjoin::TryJoinHandle;
/// use std::process as proc;
/// use std::thread as t;;
///
/// let orig_hook = std::panic::take_hook();
/// std::panic::set_hook(Box::new(move |panic_info| {
/// // invoke the default handler and exit the process
/// orig_hook(panic_info);
///     std::process::exit(1);
/// }));
///
/// t::spawn(|| agis_phiwraek::go("/tmp/a", "/tmp/b", || {
///     let mut cmd = proc::Command::new("/usr/bin/echo"); cmd.arg("Hello World!"); cmd
/// }).unwrap()).try_timed_join(std::time::Duration::SECOND * 30).unwrap();
/// ```
```

```
cheako@mx1:~/src/gitlab/rust-general/agis_phiwraek$ RUST_BACKTRACE=1 cargo test
warning: unreachable expression
  --> ylyndar_yllathyra/src/lib.rs:22:5
   |
21 |     unreachable!("Not here");
   |     ------------------------ any code following this expression is unreachable
22 |     Ok(())
   |     ^^^^^^ unreachable expression
   |
   = note: `#[warn(unreachable_code)]` on by default

warning: `ylyndar_yllathyra` (lib) generated 1 warning
   Compiling agis_phiwraek v0.1.0 (/home/cheako/src/gitlab/rust-general/agis_phiwraek)
    Finished test [unoptimized + debuginfo] target(s) in 0.22s
     Running unittests src/lib.rs (/home/cheako/src/gitlab/rust-general/target/debug/deps/agis_phiwraek-738d86a10ed7e315)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

   Doc-tests agis_phiwraek

running 1 test
test src/lib.rs - go (line 11) ... FAILED

failures:

---- src/lib.rs - go (line 11) stdout ----
Test executable failed (exit code 1).

stderr:
thread '<unnamed>' panicked at 'For testing, this should be called when `write()` is called on a closed FD.: Os { code: 9, kind: Uncategorized, message: "Bad file descriptor" }', /home/cheako/src/gitlab/rust-general/agis_phiwraek/src/lib.rs:68:10
stack backtrace:
   0: rust_begin_unwind
             at /rustc/3c17c84a386e7badf6b2c6018d172496b3a28a04/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/3c17c84a386e7badf6b2c6018d172496b3a28a04/library/core/src/panicking.rs:143:14
   2: core::result::unwrap_failed
             at /rustc/3c17c84a386e7badf6b2c6018d172496b3a28a04/library/core/src/result.rs:1784:5
   3: core::result::Result<T,E>::expect
   4: agis_phiwraek::go::{{closure}}
   5: ylyndar_yllathyra::go
   6: agis_phiwraek::go
   7: rust_out::main::_doctest_main_src_lib_rs_11_0::{{closure}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.



failures:
    src/lib.rs - go (line 11)

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 3.23s

error: test failed, to rerun pass '--doc'
```

**Comment by sunfishcode** [comment]
>        let (stdout_child, stdout) = rustix::io::pipe()?;

Pipes are unidirectional; `stdout_child` here is bound to the reading side, while `stdout` is bound to the writing side.

>        read2(
>            child.stdin.take().unwrap().into_fd(),
>            stream,
>            stream_fd,
>            unsafe { std::fs::File::from_raw_fd(stdout_child.into_raw_fd()) },
>        )

Here, the `stdout_child` is being passed into the `d2` argument of `read2`, which expects a `impl io::Write` it can write to.

It looks like the code is writing to a read-only file descriptor.

**Comment by cheako** [comment]
I'm writing this because I'm unable to find an example of this... and I need it for my project.  Thanks for taking a look and finding that, I'm struggling so much with coercing the types.

Just a feeling I get when looking in strace, looks like these FDs are being closed.  

https://gitlab.com/cheako/rust-general/-/commit/a145bdbb0aea26568ec45fa4596b3088e9d2f26a

**Comment by sunfishcode** [comment]
Rustix doesn't yet have all the `pty` APIs, but please file issues for them :-).
