### ISSUE TITLE
net/sockopt::test_sockopts test failure on s390x

### ISSUE THREAD

**Issue by decathorpe** [bytecodealliance/rustix#277]
I'm trying to update the rustix crate we have packaged for Fedora Linux in preparation for updating wasmtime to the latest version. However, I've encountered a failure when running the rustix test suite on s390x that has me slightly concerned.

Here's the relevant log output from cargo test from a build of rustix 0.33.5 (I need ^0.33 for wasmtime, and I can't easily test arbitrary versions on s390x due to limited hardware access; but it looks like the relevant code has not changed between v0.33.5...main anyway):

```
     Running `/builddir/build/BUILD/rustix-0.33.5/target/release/deps/net-c22b1583489e3ba8`
running 18 tests
test addr::encode_decode ... ok
test addr::test_unix_addr ... ok
test connect_bind_send::net_v4_acceptfrom ... ok
test connect_bind_send::net_v4_bind_any ... ok
test connect_bind_send::net_v4_connect_any ... ok
test connect_bind_send::net_v4_connect ... ok
test connect_bind_send::net_v4_sendto ... ok
test connect_bind_send::net_v4_sendto_any ... ok
test connect_bind_send::net_v6_acceptfrom ... ok
test connect_bind_send::net_v6_bind_any ... ok
test connect_bind_send::net_v6_connect ... ok
test connect_bind_send::net_v6_connect_any ... ok
test connect_bind_send::net_v6_sendto ... ok
test connect_bind_send::net_v6_sendto_any ... ok
test poll::test_poll ... ok
test sockopt::test_sockopts ... FAILED
test v4::test_v4 ... ok
test v6::test_v6 ... ok
failures:
---- sockopt::test_sockopts stdout ----
thread 'sockopt::test_sockopts' panicked at 'assertion failed: `(left == right)`
  left: `false`,
 right: `true`', tests/net/sockopt.rs:101:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
failures:
    sockopt::test_sockopts
test result: FAILED. 17 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
```

It looks like setting the `broadcast` flag does not work as expected, according to the line number in the failed assert (tests/net/sockopt.rs:101:9 from rustix 0.33.5).

I see that the commit that added those tests references some bugs in QEMU, is this one of the problems that's expected? If so, can I safely ignore this failure?

**Comment by sunfishcode** [comment]
Thanks for the report! This doesn't look related to any of the qemu bugs we've encountered, and this isn't expected. I don't currently have access to s390x hardware; I can test on qemu s390x-linux-user, though the test passes for me there.

Is it possible that Linux on s390x behaves differently than Linux on other platforms? qemu's linux-user feature is just a thin wrapper around the host OS, so it wouldn't necessarily reflect subtle differences.

Linux's socket support has a [`SO_BSDCOMPAT`](https://man7.org/linux/man-pages/man7/socket.7.html) flag, which the documentation mentions "skipping of the broadcast flag". Is it possible that `SO_BSDCOMPAT` is enabled by default by Linux, or Fedora, on s390x?

Are the tests being run under seccomp? If so, it would be interesting to see whether the seccomp configuration modifies the behavior of `socket`, `getsockopt`, or `setsockopt`.

In case it's useful, the following is a standalone C program which tests the OS' behavior:
```c
#include <sys/socket.h>
#include <assert.h>

int main(void) {
    int s = socket(AF_INET, SOCK_STREAM, 0);
    assert(s != -1);

    int one = 1;
    int r = setsockopt(s, SOL_SOCKET, SO_BROADCAST, &one, sizeof(one));
    assert(r != -1);

    int broadcast = -1;
    socklen_t optlen = (socklen_t)sizeof(broadcast);
    int q = getsockopt(s, SOL_SOCKET, SO_BROADCAST, &broadcast, &optlen);
    assert(q != -1);
    assert(optlen == sizeof(broadcast));
    assert(broadcast == 1);

    return 0;
}
```

**Comment by decathorpe** [comment]
Thanks for investigating! Having the small example program also should help me narrow down the problem. I think our build system might have seccomp filters set up for build containers (they use systemd-nspawn), so that *could* affect things, as well ... I'll report back once I know more.

**Comment by decathorpe** [comment]
This is weird: I added your test code into my build, compiled it with gcc, and ran it in the exact same environment as the rustix test suite. The program above returns with exit code 0 and does not print anything. The rustix test suite fails.

I compiled the C code with `gcc -o test test.c` and ran it with `./test`. Is there some GCC flag I'm missing for assertions to work, or is that enough?

**Comment by decathorpe** [comment]
> Ooh, I think I found a bug. Rustix is reading the value into a bool, rather than int. This may appear to "work" on little-endian platforms where the returned value of 1 is in the least-significant byte, but of course, it's a bug either way.

That indeed looks like the culprit 👍🏼 

I tried backporting the patch from your PR to 0.33.5, but I gave up on that because it didn't apply cleanly, and I was out of my depth trying to manually apply the changes on top of unrelated changes in the getsockopt / setsockopt functions :( Given that the new wasmtime 0.36 branch is still using rustix 0.33.5, would it be possible to backport your changes to the 0.33 branch as well?

**Comment by sunfishcode** [comment]
Will do. I've now cherry-picked the patch, along with a few other bug-fix patches, onto the [v0.33.x branch]](https://github.com/bytecodealliance/rustix/tree/v0.33.x). I'll run some tests to make sure everything still works, and then make a release.

**Comment by sunfishcode** [comment]
Also, just for the record, as mentioned in #280, this bug doesn't involve out-of-bounds memory accesses. The kernel truncates the value it writes, rather than writing out of bounds, so it just produces the wrong value, on big-endian platforms.

**Comment by sunfishcode** [comment]
@decathorpe 0.33.6 is now released, with the fix. I've now posted https://github.com/bytecodealliance/wasmtime/pull/4022 to update Wasmtime.
