### ISSUE TITLE
`as u64` when left hand side of assignment can be 32 bit

### ISSUE THREAD

**Issue by AsafFisher** [bytecodealliance/rustix#324]
Cant `iov_len` be `u32`?
https://github.com/bytecodealliance/rustix/blob/23841ae92b5d1ef772bb9a91dff067f67e5ec070/src/imp/linux_raw/io/io_slice.rs#L26

**Comment by sunfishcode** [comment]
Yes, it appears you're right. Would you mind submitting a PR fixing this?

**Comment by AsafFisher** [comment]
Sure (:

**Comment by sunfishcode** [comment]
This is now released in 0.34.7.
