### ISSUE TITLE
Code Style

### ISSUE THREAD

**Issue by AsafFisher** [bytecodealliance/rustix#328]
Why not do `into()` instead of `OwnedFd::from`
https://github.com/bytecodealliance/rustix/blob/23841ae92b5d1ef772bb9a91dff067f67e5ec070/src/imp/linux_raw/conv.rs#L730

**Comment by sunfishcode** [comment]
`.into()` would probably work there. I don't think I had any special reason for writing it that way, except perhaps that I was just trying to be careful about which `OwnedFd` it was using, since it's a bit subtle that there are two.
