### ISSUE TITLE
How can I get f_frsize?

### ISSUE THREAD

**Issue by al8n** [bytecodealliance/rustix#374]
Hi, is there a way to get `f_frsize` by `statfs`?

**Comment by sunfishcode** [comment]
Yes, [`std::fs::statfs`](https://docs.rs/rustix/latest/rustix/fs/fn.statfs.html) returns a [`Statfs`](https://docs.rs/rustix/latest/rustix/fs/type.StatFs.html), which (on platforms that support it) has a `f_frsize` field.

**Comment by al8n** [comment]
Does this crate have `statvfs` equivalent?

**Comment by sunfishcode** [comment]
It does not currently. 

`statvfs` appears to be POSIX's attempt to define a portable interface to the wildly differing OS `statfs` structs out there, however the situation is still murky; FreeBSD for example [describes it](https://www.freebsd.org/cgi/man.cgi?query=statvfs&apropos=0&sektion=0&manpath=FreeBSD+14.0-current&arch=default&format=html#DESCRIPTION) as:

> The statvfs() and fstatvfs() functions fill the structure pointed to by
     buf with garbage.	This garbage will occasionally bear resemblance	to
     file system statistics, but portable applications must not	depend on
     this. 

Could you say which fields of `statvfs` you need? If you just need `f_frsize` or a few others in a portable way, it's possible rustix may be able to provide those in a portable way.

**Comment by al8n** [comment]
Hi, I only need `f_frsize` currently.

**Comment by sunfishcode** [comment]
Looking into it more, it looks like rustix can just go ahead and provide a `statvfs` function. I've submitted https://github.com/bytecodealliance/rustix/pull/375 to implement this.

**Comment by al8n** [comment]
> Looking into it more, it looks like rustix can just go ahead and provide a `statvfs` function. I've submitted #375 to implement this.

Thank you so much!

**Comment by sunfishcode** [comment]
This is now fixed in #375 and released in rustix 0.35.7.
