### ISSUE TITLE
Make it possible to selectively use `libc` for `param` mod

### ISSUE THREAD

**Issue by ianks** [bytecodealliance/rustix#382]
In the `linux_raw` backend, the `param` module must be loaded before any user-defined constructor functions. In our use case we are building a Ruby native gem, and cannot assure that our dylib is loaded early enough, so [we end up failing this assertion](https://github.com/bytecodealliance/rustix/blob/1ceb659b9f6ec35628b6dddee3a2ef881d460af4/src/backend/linux_raw/param/auxv.rs#L183).

This can be fixed by using the `use-libc`, but that also means we lose the benefits of Rust implementation (inlining, etc.) for other parts of this crate. Would it be possible to opt-in to just using libc for _the just `param` module_ (something like `use-libc-param`)?

**Comment by sunfishcode** [comment]
Thanks for the report! use-libc is a reasonable workaround. I'll look into ways we could implement this.

**Comment by sunfishcode** [comment]
I've now posted #385 with a fix for this.

**Comment by ianks** [comment]
Wow, what a quick turn around. Thank you so much @sunfishcode!

**Comment by sunfishcode** [comment]
This is now released in 0.35.9.
