### ISSUE TITLE
mmap_anonymous will exhaust memory on `riscv64gc-unknown-linux-gnu` when memory size is big.

### ISSUE THREAD

**Issue by yuyang-ok** [bytecodealliance/rustix#400]
I didn't know this issue related to this project or `qemu-riscv64`.

![image](https://user-images.githubusercontent.com/96557710/190363912-73d56b34-e196-448b-8ed9-48489d7d592c.png)

[abc.tar.gz](https://github.com/bytecodealliance/rustix/files/9573740/abc.tar.gz)

**Comment by yuyang-ok** [comment]
I test two version of qemu, all of there have this problem.
~~~
yuyang@yuyang-Inspiron-7590:~/projects/wasmtime/tests$ qemu-riscv64  --version 
qemu-riscv64 version 7.0.94 (v7.1.0-rc4)
Copyright (c) 2003-2022 Fabrice Bellard and the QEMU Project developers
~~~

~~~
yuyang@yuyang-Inspiron-7590:~/projects/abc-rust$ qemu-riscv64-static --version 
qemu-riscv64 version 6.2.0 (Debian 1:6.2+dfsg-2ubuntu6.4)
Copyright (c) 2003-2021 Fabrice Bellard and the QEMU Project developers
~~~

**Comment by bjorn3** [comment]
Did you use the version of qemu that wasmtime uses in CI? It has a patch to fix a bug in qemu that I believe is the same as this one.

**Comment by yuyang-ok** [comment]
No, I am using from official.

**Comment by yuyang-ok** [comment]
No, I am using from official.

**Comment by yuyang-ok** [comment]
I met `qemu-riscv64` problem before.
https://bytecodealliance.zulipchat.com/#narrow/stream/206238-general/topic/.E2.9C.94.20target-riscv64.20.20decommit_table_pages.2E
I download the latest version qemu , this problem solved.
the two problem are related?

**Comment by sunfishcode** [comment]
This doesn't appear to be a rustix bug; I can reproduce the same behavior with libc:
```rust
        let r = libc::mmap(
            ptr::null_mut(),
            6666 << 30,
            libc::PROT_NONE,
            libc::MAP_PRIVATE | libc::MAP_ANONYMOUS,
            -1,
            0,
        );
        assert_ne!(r, libc::MAP_FAILED);
```

**Comment by yuyang-ok** [comment]
I did some test using c.
~~~
#include <stdio.h>
#include <sys/mman.h>
#include <errno.h>

int main(int argc, char **argv)
{
    void *addr;
    size_t length = 6666 << 30;
    addr = mmap(NULL, length, PROT_NONE, MAP_PRIVATE | MAP_ANONYMOUS, -1, 0);
    if (addr == -1)
    {
        printf("errno:%d\n", errno);
        return 1;
    }
    printf("ptr:%d", addr);
    getchar();
    return 0;
}

yuyang@yuyang-Inspiron-7590:~/projects/abc-rust/src$ /home/yuyang/projects/qemu/build/qemu-riscv64 -L /usr/riscv64-linux-gnu -E LD_LIBRARY_PATH=/usr/riscv64-linux-gnu/lib ./a.out 
errno:12
~~~
![image](https://user-images.githubusercontent.com/96557710/190534718-2c89ad71-4fac-41ec-af5f-b7cb63254a39.png)

**Comment by yuyang-ok** [comment]
@bjorn3  I patched the code.
![image](https://user-images.githubusercontent.com/96557710/190536315-40362fc0-1ff8-4106-a1d2-c0f012876985.png)
I am using qemu.
~~~
yuyang@yuyang-Inspiron-7590:~/projects/qemu/build$ git log 
commit 9a99f964b152f8095949bbddca7841744ad418da (HEAD -> master, tag: v7.1.0-rc4, origin/master, origin/HEAD)
Author: Richard Henderson <richard.henderson@linaro.org>
Date:   Wed Aug 24 19:27:56 2022 -0700

    Update version for v7.1.0-rc4 release
    
    Signed-off-by: Richard Henderson <richard.henderson@linaro.org>
~~~

I still get the error code `12`.

**Comment by sunfishcode** [comment]
That C program isn't equivalent because it's evaluating `6666 << 30` as type `int`, which overflows, producing a different value when subsequently converted to `size_t`.

**Comment by yuyang-ok** [comment]
@sunfishcode  sorry.
~~~
#include <stdio.h>
#include <sys/mman.h>
#include <errno.h>

int main(int argc, char **argv)
{
    void *addr;
    int a = 6666;
    size_t length = a << 30;
    addr = mmap(NULL, length, PROT_NONE, MAP_PRIVATE | MAP_ANONYMOUS, -1, 0);
    if (addr == MAP_FAILED)
    {
        printf("errno:%d\n", errno);
        return 1;
    }
    getchar();
    return 0;
}
yuyang@yuyang-Inspiron-7590:~/projects/abc-rust/src$ /home/yuyang/projects/qemu/build/qemu-riscv64 -L /usr/riscv64-linux-gnu -E LD_LIBRARY_PATH=/usr/riscv64-linux-gnu/lib ./a.out 
errno:12
~~~
I still get this error code.

**Comment by yuyang-ok** [comment]
[Uploading abc.tar.gz…]()

**Comment by yuyang-ok** [comment]
[abc.tar.gz](https://github.com/bytecodealliance/rustix/files/9580372/abc.tar.gz)

**Comment by sunfishcode** [comment]
That C code still computes 6666 << 30 in type int, so it still overflows before converting to size_t.

**Comment by yuyang-ok** [comment]
@sunfishcode ok, thanks.
