### ISSUE TITLE
Make `rustix::io::procfs::proc_self_file` public

### ISSUE THREAD

**Issue by niluxv** [bytecodealliance/rustix#423]
I'm interested in opening `/proc/self/status` while checking that it is indeed procfs (like the `rustix::io::proc_self_*` functions do). Would it be possible to either make `proc_self_file` public or add a `proc_self_status` function?

**Comment by sunfishcode** [comment]
I've opened #424 to add `proc_self_status`.

Unless there are other considerations, I prefer this to making `proc_self_file` public, as `proc_self_mem` has the ability to open `/proc/self/mem`. Rustix in general doesn't prevent user code from opening `/proc/self/mem` manually, and it [isn't a soundness problem](https://doc.rust-lang.org/stable/std/os/unix/io/index.html#procselfmem-and-similar-os-features), but nonetheless, I'd like to avoid adding APIs which have the ability to access `/proc/self/mem` when we can.
