### ISSUE TITLE
[Q] `no_std` and nightly rust

### ISSUE THREAD

**Issue by niluxv** [bytecodealliance/rustix#426]
According to the `Cargo.toml`, disabling the `std` feature requires nightly rust.
```
# This enables use of std. Disabling this enables `#![no_std], and requires
# nightly Rust.
std = ["io-lifetimes"]
```

However, it seems I can just build `rustix` on the latest stable with `--no-default-features --features all-apis`. Am I missing something? Or has this changed since that comment was written?

label: question

**Comment by sunfishcode** [comment]
It may have started working in Rust 1.64 when [`CStr` became available in `core`](https://blog.rust-lang.org/2022/09/22/Rust-1.64.0.html#c-compatible-ffi-types-in-core-and-alloc). I've now submitted #427 which updates that comment.
