### ISSUE TITLE
feat: wordexp(3)

### ISSUE THREAD

**Issue by WhyNotHugo** [bytecodealliance/rustix#432]
Is it feasible to provide a function to call [wordexp(3)](https://linux.die.net/man/3/wordexp)?

The function itself is from POSIX.1-2001., and a super useful shortcut to glob+variable interpolation.

**Comment by sunfishcode** [comment]
Rustix's goal is to just support system calls and syscall-related data structures. I expect it's technically possible to make a safe API around `wordexp`, but it wouldn't need any of rustix's internal infrastructure, so it could live in a separate crate.

**Comment by WhyNotHugo** [comment]
Right, `wordexp` is just a POSIX function, but it's provided by libc and so doesn't involve a system call.
