### ISSUE TITLE
`exit` syscall

### ISSUE THREAD

**Issue by cottnn** [bytecodealliance/rustix#435]
I was looking through the documentation and I noticed that there's no `exit` syscall. Did I miss it somehow or is it not documented?

**Comment by sunfishcode** [comment]
There is an exit_group function, though it's in a doc(hidden) module because most programs should use std::process::exit instead. Can you say more about your use case?

**Comment by cottnn** [comment]
I'm writing a no_std program, I also don't link to libc, so I need to use syscalls directly

**Comment by sunfishcode** [comment]
Ah, so it is there; if you enable the "runtime" feature and use it as `rustix::runtime::exit_group`, you'll get it. It's hidden, because it basically depends on there being no `libc` in charge of the process, since the `libc` crate can be used in no_std programs too.

**Comment by sunfishcode** [comment]
If you have any further questions, please reopen this or file a new issue!
