### ISSUE TITLE
`proc_self_status` errors when `/proc/self/status` is root owned

### ISSUE THREAD

**Issue by niluxv** [bytecodealliance/rustix#441]
This happens when the process is not dumpable (which can have a variety of reasons, see [the proc manpage](https://man7.org/linux/man-pages/man5/proc.5.html) under "Files and directories" and [the prctl manpage](https://man7.org/linux/man-pages/man2/prctl.2.html) under "PR_SET_DUMPABLE").

The error that is returned:
```
Os { code: 95, kind: Uncategorized, message: "Operation not supported" }
```

(Note that `/proc/self/status` ~~is not root owned~~; the user has sufficient permissions to open that file. `std::fs::File::open` works without problems.)

**Comment by sunfishcode** [comment]
From some experimentation, it appears the problem is related to the `NOATIME` flag, which the implementation of `proc_self_status` is using.

In this code:
```rust
use rustix::fs::{openat, cwd, Mode, OFlags};

fn main() {
    dbg!(openat(cwd(), "/proc/self/status", OFlags::RDONLY, Mode::empty()));
    dbg!(openat(cwd(), "/proc/self/status", OFlags::RDONLY|OFlags::NOATIME, Mode::empty()));
    rustix::process::set_dumpable_behavior(rustix::process::DumpableBehavior::NotDumpable).unwrap();
    dbg!(openat(cwd(), "/proc/self/status", OFlags::RDONLY, Mode::empty()));
    dbg!(openat(cwd(), "/proc/self/status", OFlags::RDONLY|OFlags::NOATIME, Mode::empty()));
}
```
The last line fails. So it seems there's some conflict between `O_NOATIME` and the process being non-dumpable.

I don't have any theories as to why that might be, but most likely the fix is to remove `O_NOATIME`, since that isn't really important here anyway.

**Comment by niluxv** [comment]
Ah, thank you for looking into this! I would have had no clue. Now reading the [manual page](https://man7.org/linux/man-pages/man2/open.2.html) it indeed says

> This flag can be employed only if one of the following conditions is true:
>  *  The effective UID of the process matches the owner UID of the file.
>  *  The calling process has the CAP_FOWNER capability in its user namespace and the owner UID of the file has a mapping in the namespace.
