### ISSUE TITLE
Update feature gates?

### ISSUE THREAD

**Issue by SUPERCILEX** [bytecodealliance/rustix#445]
I've been poking around the code and saw this: https://github.com/bytecodealliance/rustix/blob/74312285f64f0ae2a547c1911221fbabfa5c75c0/src/backend/linux_raw/mod.rs#L34

In general, is the stdlib version of I/O safety used or is a copy included in rustix? It would be nice if only the stdlib version was used (assuming the std feature is enabled).

**Comment by sunfishcode** [comment]
It does use the std version when the std feature is enabled, and the Rust version is >= 1.63 (when I/O safety was stabilized).

The copy of `OwnedFd` etc. in the tree is only used in the no_std configuration.

**Comment by SUPERCILEX** [comment]
That's good to know, thanks. Can the feature gate be re-enabled then?

**Comment by sunfishcode** [comment]
Possibly. It'll probably take some other fiddling, but I'll take a quick look.

**Comment by sunfishcode** [comment]
I've now posted https://github.com/bytecodealliance/rustix/pull/449.

**Comment by SUPERCILEX** [comment]
Awesome, thanks!

**Comment by sunfishcode** [comment]
Fixed in #449.
