### ISSUE TITLE
Unclear features: libc, io-lifetimes, use-libc-auxv

### ISSUE THREAD

**Issue by SUPERCILEX** [bytecodealliance/rustix#447]
It'd be nice if these features were documented a little better. Here's my understanding:
- std enables io-lifetimes, which is presumably just a shim on rust >= 1.63
- By default, libc is NOT used
- Whatever auxiliary vectors are, that uses the libc version by default.

**Comment by sunfishcode** [comment]
> It'd be nice if these features were documented a little better. Here's my understanding:
> 
>     * std enables io-lifetimes, which is presumably just a shim on rust >= 1.63

Yes.

>     * By default, libc is NOT used

The libc backend is the default backend on all platforms other than Linux, and on all architectures that rustix doesn't have native syscall support for.

>     * Whatever auxiliary vectors are, that uses the libc version by default.

Yes.

**Comment by SUPERCILEX** [comment]
Interesting, thanks for the confirmation. I think the response to this issue is documentation enough since the README already says linux_raw is used by default. People should be able to find this issue if they want the details on how the feature gates are used.
