### ISSUE TITLE
Cirrus CI not running

### ISSUE THREAD

**Issue by asomers** [bytecodealliance/rustix#470]
rustix has a .cirrus.yml file for FreeBSD, but it doesn't look like it's ever run.  In order to make FreeBSD CI work, follow the instructions here: https://cirrus-ci.org/guide/quick-start/ .  After that, I can help configure it, if you like.

**Comment by sunfishcode** [comment]
Yeah. I need to request this from the bytecodealliance admins. At present, I have a fork where I run it before releases. And there is a cargo check for FreeBSD in CI here that catches most problems. But I agree, it'd be better to have it enabled here. I'll look into it.

**Comment by sunfishcode** [comment]
Cirrus CI is now running.
