### ISSUE TITLE
URGENT: patch out RawDir for the next release too

### ISSUE THREAD

**Issue by SUPERCILEX** [bytecodealliance/rustix#472]
@sunfishcode pretty sure I done goofed again. Was listening to the ghost cell podcast and Ralf talked about how you can access all of the elements of the Iterator at the same time thanks to the non-aliasing references. Anyway, I was like, "doesn't raw dir work that way since the lifetime is bound to the buffer?" And then: "Oh shit, we reuse that buffer."

TL;DR: pretty sure people can accumulate entry references into some other structure, but they'll be garbage once the buffer restarts. Need to double check tomorrow. Somehow need lifetime that is bound to the buffer so it can't be dropped but also blocks aliasing so every call to next requires dropping the previous entry.

**Comment by SUPERCILEX** [comment]
Preliminary research indicates that GATs are required. Need to investigate further.

**Comment by sunfishcode** [comment]
Thanks for the heads up! I've now created a 0.36 branch, so we can do 0.36 releases without pulling in the `RawDir` changes for now.

**Comment by SUPERCILEX** [comment]
Alrighty, I put up a patch.

I think we finally got this dang thing locked down. Safety is so hard lol. :sweat_smile:
