### ISSUE TITLE
Sparse file support for `lseek`?

### ISSUE THREAD

**Issue by sharifhsn** [bytecodealliance/rustix#480]
On Linux and some other POSIX systems, [`lseek`](https://man7.org/linux/man-pages/man2/lseek.2.html) supports two additional values for `whence` relating to sparse files, `SEEK_HOLE` and `SEEK_DATA`. I believe these should be supported by `rustix`.

For reference, some filesystems have files with large amounts of zero data that can be optionally marked "sparse", and these sections won't be allocated on disk. This feature can be exposed to userspace applications to improve the performance of some operations, like `cp`.

Although this is technically not a part of the POSIX standard, it has been proposed for issue 8.

As an example of prior art, [`nix` already exposes this ability](https://docs.rs/nix/latest/nix/unistd/fn.lseek.html).

**Comment by sunfishcode** [comment]
Yes, rustix should add this. It will require Rustix to switch to its own `SeekFrom` type, rather than just using std's, but I think that makes sense to do.

**Comment by sharifhsn** [comment]
Great! I'll submit a PR for this today if you want.

**Comment by sunfishcode** [comment]
Sure, sounds great!
