### ISSUE TITLE
Add mount syscall?

### ISSUE THREAD

**Issue by SUPERCILEX** [bytecodealliance/rustix#491]
It'd be nice to have. Nix version: https://docs.rs/nix/latest/nix/mount/index.html

**Comment by sunfishcode** [comment]
Yes, this makes sense and looks straightforward. I myself won't be able to implement this for the time being but if anyone's interested I'd be happy to review a patch.

**Comment by SUPERCILEX** [comment]
Sounds good, I'll give it a go.
