### ISSUE TITLE
Remove the windows-sys dependency

### ISSUE THREAD

**Issue by notgull** [bytecodealliance/rustix#591]
The `windows-sys` crate has gone through quite a bit of version churn, see microsoft/windows-rs#1720. Therefore, some of the foundational crates in the ecosystem have been manually creating Win32 bindings for what they need. `rustix` may want to migrate in this direction as well.

**Comment by sunfishcode** [comment]
I've seen https://github.com/Amanieu/parking_lot/pull/374 which seems to contain the main rationale for this, and I'm surprised that there seems to be an absence of any kind of numbers describing how much compile time this saves, or even how much filesystem cache space or network traffic it saves or anything else. I'm not eager to take on new kinds of complexity to solve an abstract problem.

**Comment by Jake-Shadle** [comment]
I plan on elucidating all of this in a blog post soon, parking_lot was simply the first crate I chose while iterating on a generation tool since it is foundational and thus has an outsize ecosystem effect, and was also just low hanging fruit that I was fairly confident would be merged.

**Comment by notgull** [comment]
Closing for now.
