### ISSUE TITLE
Linking error: undefined symbol `syncfs` on Android

### ISSUE THREAD

**Issue by sinhpham** [bytecodealliance/rustix#617]
I'm having a linking error with rustix version >= 0.37.6 (since https://github.com/bytecodealliance/rustix/commit/668569a79274dfd79b9511e33faa19c95a743642)

```
ld: error: undefined symbol: syncfs
  >>> referenced by rustix.36179ca0-cgu.2
  >>>               rustix-9faabf2da35bf71d.rustix.36179ca0-cgu.2.rcgu.o:(rustix::backend::fs::syscalls::syncfs::h3dac34f3cc3ae8b0) in archive [redacted]
  clang++: error: linker command failed with exit code 1 (use -v to see invocation)
  ninja: build stopped: subcommand failed.
```

Looks like I (or rustix) need to include a dynamic lib in the linking phase?

**Comment by sunfishcode** [comment]
Looks like rustix needs to change to avoid depending on `syncfs` statically. I've now submitted #618 to fix this.

Rustix can't guarantee that `syncfs` will work at runtime, and some Android platforms are configured to kill any process which executes a system call they don't recognize, but with #618, you'll at least have the option of trying!

**Comment by sinhpham** [comment]
Thank you for the quick fix.
