### ISSUE TITLE
[Bug Report] Crate not Documentable with Rust 1.69.0

### ISSUE THREAD

**Issue by kevinmatthes** [bytecodealliance/rustix#624]
With the latest available stable Rust version, 1.69.0, it is not possible anymore to document this crate.  The compiler panics and exits due a documentation link not being resolvable.

I realise that this behaviour is first of all a critical compiler error of `rustc` but during my tests, every project with this crate, v0.36.4 or later, as dependency was not documentable.  Thus, I assumed that you should probably know about this issue, as well.

**Comment by sunfishcode** [comment]
Thanks for the report! This turns out to be triggered by a doc comment which is redundant anyway, so I filed #627 to the 0.36 release branch removing the comment, which avoids the cargo doc abort. It's already removed on main and 0.37.

**Comment by sunfishcode** [comment]
This is now fixed in 0.36.13.

**Comment by kevinmatthes** [comment]
Thank you very much for your support!
