### ISSUE TITLE
Incorrect bitflags dependency version

### ISSUE THREAD

**Issue by Florob** [bytecodealliance/rustix#629]
34841fc25bf1a0cdcb043295e0bf515f4dd3a77a introduced a call to bitflags' `difference()` function, which was only introduced in bitflags 1.3.1 (maybe 1.3.0, but that was yanked). rustix only specifies 1.2.1 as dependency though.

This caused build failures after the 0.37.14 release. I'm actually a bit surprised `cargo update` doesn't also bump the bitflags version to 1.3.2, but the dependency is wrong either way.

**Comment by sunfishcode** [comment]
Thanks for the report! I've now submitted #630 to bump the dependency to 1.3.2.
