### ISSUE TITLE
error [E0599] on rustix compilation

### ISSUE THREAD

**Issue by ghost** [bytecodealliance/rustix#656]
rustc version used 1.69.0 and 1.64.0

when I try to install a program that needs to compile rustix as a dependency i get the following error:

error[E0599]: no method named `difference` found for struct `backend::fs::types::AtFlags` in the current scope
/home/user/.cargo/registry/src/github.com-xxxxxxxxxxx/rustix-0.37.14/src/backend/linux_raw/fs/syscalls.rs:1396:10 

1395 |       if !flags
     |  _________-
1396 | |         .difference(AtFlags::EACCESS | AtFlags::SYMLINK_NOFOLLOW)
     | |         -^^^^^^^^^^ method not found in `AtFlags`
     | |_________|
     |
     |
    ::: /home/user/.cargo/registry/src/github.com-xxxxxxxxxxx/rustix-0.37.14/src/backend/linux_raw/fs/types.rs:23:1
     |
23   | / bitflags! {
24   | |     /// `AT_*` constants for use with [`openat`], [`statat`], and other `*at`
25   | |     /// functions.
26   | |     ///
...    |
53   | |     }
54   | | }
     | |_- method `difference` not found for this struct

**Comment by sunfishcode** [comment]
Thanks for the report! This is fixed in rustix v0.37.15. You can also avoid the error by updating the bitflags crate as with running `cargo update --package=bitflags --precise=1.3.2`.

**Comment by sunfishcode** [comment]
Thanks for confirming!
