### ISSUE TITLE
Test `test_ioctl_fioclone` fails on BTRFS

### ISSUE THREAD

**Issue by oxalica** [bytecodealliance/rustix#658]
Seems `ioctl_ficlone` for the same file succeed on BTRFS, while the test expects a failure.
https://github.com/bytecodealliance/rustix/blob/ec767e8768a07e5de35f41a3b2042c83bf79a82c/tests/io/ioctl.rs#L31

I couldn't find any doc in [`ioctl_ficlone(2)`](https://man7.org/linux/man-pages/man2/ioctl_ficlone.2.html#ERRORS) about why this must fail. It only contains,
> XFS and Btrfs do not support _overlapping_ reflink ranges in
> the same file.

**Comment by sunfishcode** [comment]
I think the test was assuming `dest` was opened `O_WRONLY` which would evoke an `EBADF`, but `tempfile` opens its file `O_RDWR` (as it should). I posted https://github.com/bytecodealliance/rustix/pull/659 with a possible fix.

**Comment by sunfishcode** [comment]
Fixed in #659.
