### ISSUE TITLE
Question: Does `rustix` provides any api like `libc::gethostname`?

### ISSUE THREAD

**Issue by al8n** [bytecodealliance/rustix#663]

**Comment by sunfishcode** [comment]
No, rustix is scoped to just "system call" wrappers. `gethostbyname` is a higher-level library function.

**Comment by sunfishcode** [comment]
Oops, I misread the title here. For `gethostname`, you can use `rustix::process::uname().nodename()`.

**Comment by al8n** [comment]
> Oops, I misread the title here. For `gethostname`, you can use `rustix::process::uname().nodename()`.

Thank you very much!
