### ISSUE TITLE
broken no_std support on windows

### ISSUE THREAD

**Issue by MindMayhem** [bytecodealliance/rustix#682]
Hi, no_std completely broken on rustix (especially "net" feature), compile with `default-features=false` and `#![no_std]` in _main.rs_ causes many errors like 

```
src\backend\libc\io_lifetimes.rs:21:28
   |
21 |     fn as_raw_fd(&self) -> RawFd;
   |                            ^^^^^ not found in this scope
   |
help: consider importing this type alias
   |
6  + use crate::io::fd::RawFd;
```

not found function:
```
src\io\fd\owned.rs:95:29
   |
95 |         let fd = crate::io::fcntl_dupfd_cloexec(self, 0)?;
   |                             ^^^^^^^^^^^^^^^^^^^ not found in `crate::io`

   ```

also, there's a std import that uncovered under `#[cfg(feature = "std")]`:

```
src\backend\libc\io\poll_fd.rs:9:5
  |
9 | use std::fmt;
  |     ^^^ use of undeclared crate or module `std`
  ```
  
  
  Cargo.toml import line:
  ```
  rustix = {version = "0.37.19", features=["net","io-lifetimes","use-libc"], default-features=false}
  ```

**Comment by MindMayhem** [comment]
tried to build with `rustc-dep-of-std` feature, got error during compilation:
```
   Compiling bitflags v1.3.2
error[E0433]: failed to resolve: could not find `prelude` in `core`
```

**Comment by niluxv** [comment]
What is the target platform? Windows? (I think that is the only platform where `no_std` is broken.)

**Comment by MindMayhem** [comment]
> What is the target platform? Windows? (I think that is the only platform where `no_std` is broken.)

yes, target platform is `x86_64-pc-windows-msvc`

**Comment by MindMayhem** [comment]
found these in `src\backend\libc\mod.rs`:

```
#[cfg(windows)]
pub(crate) mod fd {
    pub use std::os::windows::io::{
        AsRawSocket as AsRawFd, AsSocket as AsFd, BorrowedSocket as BorrowedFd,
        FromRawSocket as FromRawFd, IntoRawSocket as IntoRawFd, OwnedSocket as OwnedFd,
        RawSocket as RawFd,
    };
    pub(crate) use windows_sys::Win32::Networking::WinSock::SOCKET as LibcFd;
}
```
seems like we need no_std implementation of these imports, probably can be solved with copying related modules from std

**Comment by niluxv** [comment]
I think porting the windows support to become `no_std` compatible would not be entirely trivial. Note that you are passing the `io-lifetimes` feature, but the `io_lifetimes` crate also requires `std`.

Do you have a use case for `no_std` on windows? I mean, `no_std` is mostly useful for embedded systems and the like...

**Comment by niluxv** [comment]
Seems like we commented almost simultaniously ;). Yes, it would be mostly copying from code from `std`.

**Comment by MindMayhem** [comment]
> I think porting the windows support to become `no_std` compatible would not be entirely trivial. Note that you are passing the `io-lifetimes` feature, but the `io_lifetimes` crate also requires `std`.
> 
> Do you have a use case for `no_std` on windows? I mean, `no_std` is mostly useful for embedded systems and the like...

i have reason for no_std, but that's under NDA, so i can't tell 
thanks for info that  `io-lifetimes` under std, but  `io-lifetimes` was removed in 0.38-planning branch

i wil try to copy-paste socket-related modules from std, let's see what comes of it

**Comment by niluxv** [comment]
#692 adds no_std support for windows.
