### ISSUE TITLE
Question about io_uring_cqe

### ISSUE THREAD

**Issue by jkvargas** [bytecodealliance/rustix#684]
Can you guys, please, explain why big_cqe field was left out of io_uring_cqe struct.

**Comment by sunfishcode** [comment]
It's an oversight. I've now opened https://github.com/bytecodealliance/rustix/pull/685 to add it. It'll need to be in the 0.38 release, because it requires removing `Copy` and `Clone` from `io_uring_cqe`, because `big_cqe` is an incomplete array field.
