### ISSUE TITLE
Protocol values for `ETH_P_ALL` etc.

### ISSUE THREAD

**Issue by sunfishcode** [bytecodealliance/rustix#688]
Rustix is missing `Protocol` values for `ETH_P_ALL` and others.

**Comment by e-zann** [comment]
If I saw it correctly, all values of [linux/if_ether.h](https://github.com/spotify/linux/blob/master/include/linux/if_ether.h) are missing.

**Comment by e-zann** [comment]
Really nice work, i just read the commit. 
It seems I have a lot to create and test for tomorrow.

**Comment by e-zann** [comment]
@sunfishcode 
I think i'm be at a loss:

cargo.toml
`[dependencies]
rustix = { version = "0.38.0-alpha.0", features = ["all-apis"] }`

main.rs -> socket() call:
`let sock = socket( AddressFamily::PACKET, SocketType::RAW, Protocol::ETH_P_ALL ).unwrap();`


![grafik](https://github.com/bytecodealliance/rustix/assets/110538861/8d11c574-afe4-4350-91b5-c1da88a2af8f)

**Comment by e-zann** [comment]
I tested the ETH_P_ALL Protocol, that should be the hex value of 0x0003.

socket:
`let sock = socket( AddressFamily::PACKET,  SocketType::RAW, Some(Protocol::from(eth::ALL))).unwrap();`

But with strace it shows that the Protocol value is wrong:

![grafik](https://github.com/bytecodealliance/rustix/assets/110538861/43f86b02-95c3-4862-99f1-62bcfe71b839)

**Comment by e-zann** [comment]
Same with arp:

ETH_P_ARP = 0x0806

And rustix, strace: socket(AF_PACKET, SOCK_RAW, htons(0x608 /* ETH_P_??? */)) = 4

**Comment by e-zann** [comment]
Update:
0x003 = 3
0x300 = 768

`pub const ALL: Protocol = Protocol(unsafe { RawProtocol::new_unchecked(768) });`

Dirty, but it works.
![grafik](https://github.com/bytecodealliance/rustix/assets/110538861/f5efd6bf-9710-44bd-94d0-c51f08d3d3ac)

Is this an endian-type issue ?

**Comment by sunfishcode** [comment]
Thanks for testing this! Indeed, I missed that the `AF_PACKET` family expects its protocols to be in 16-bit big-endian. I've now added a patch to #691 which implements that.

**Comment by e-zann** [comment]
![grafik](https://github.com/bytecodealliance/rustix/assets/110538861/3b3ee309-1e7a-423b-b2e9-0f45a1b0e2b7)

Nice, thank you a lot, it works directly.
