### ISSUE TITLE
Missing shm_open?

### ISSUE THREAD

**Issue by Arisa-Snowbell** [bytecodealliance/rustix#705]

**Comment by Arisa-Snowbell** [comment]
Okay, It seems just creating file normal way in Rust works completely okay, I just have to specify /dev/shm prefix to the shared memory name.
So maybe there is no need to add it? Not sure if this is a completely correct way to do that but it seems to be what glibc does.

**Comment by valpackett** [comment]
> Not sure if this is a completely correct way to do that but it seems to be what glibc does.

It's a Linux-specific way; on other systems shm fd's aren't necessarily implemented as files on the filesystem.
