### ISSUE TITLE
eventfd is not available on FreeBSD 12

### ISSUE THREAD

**Issue by Nilstrieb** [bytecodealliance/rustix#716]
20c13d4d1f1107feb5c8468cb7ba0f4aeda4ecca added support for `eventfd` on FreeBSD. FreeBSD has eventfd in [FreeBSD 13](https://man.freebsd.org/cgi/man.cgi?query=eventfd&apropos=0&sektion=0&manpath=FreeBSD+13.0-RELEASE+and+Ports&arch=default&format=html), but not in [FreeBSD 12](https://man.freebsd.org/cgi/man.cgi?query=eventfd&apropos=0&sektion=0&manpath=FreeBSD+12.4-RELEASE&arch=default&format=html). FreeBSD 12 is [still supported upstream](https://www.freebsd.org/releases/) and therefore rustc builds its distribution builds using FreeBSD 12, which fails because of the rustix change. `rustix::backend::syscalls::eventfd` gets linked into `librustc_driver.so` despite not being used (I'm not sure why, maybe something weird around dylibs?) and then it fails to link with the main binary because of the undefined symbol.

See https://github.com/rust-lang/rust/pull/113046#issuecomment-1616094626

**Comment by sunfishcode** [comment]
This is now fixed in #718 and #717, and released in 0.38.2 and 0.37.22. I've also now re-enabled FreeBSD 12 testing, and fixed a few other additional minor issues that turned up.
