### ISSUE TITLE
Could be possible to remove the binaries (*.a) from the crate?

### ISSUE THREAD

**Issue by germag** [bytecodealliance/rustix#720]
rustix includes few lib binaries as librustix_outline_{arch}.a, and also are checksumed in the `.cargo-checksum.json`

This makes packaging apps that have rustix as a dependency complicated on distributions that do not allow binaries in vendorized dependencies. Could be possible to do not include the *.a in the crate?

**Comment by nbdd0121** [comment]
For context, Fedora has issues creating packages that depend on rustix due to the binaries violating their guidelines https://src.fedoraproject.org/rpms/virtiofsd/pull-request/2#comment-145690

**Comment by sunfishcode** [comment]
rustix 0.38 removed most of the prebuilt archives, and #722 will remove the 32-bit x86 archives; after that, the only archives left are for mips and powerpc, where Rust's inline asm is still marked experimental.

Perhaps the next step here is to change mips and powerpc to default to the libc backend, which would eliminate the last of the archives.

**Comment by nbdd0121** [comment]
Or depend on `cc` for MIPS and PowerPC?

**Comment by sunfishcode** [comment]
That would require every repo that has rustix as a transitive dependency and that has MIPS or Power in their CI to add code to their CI scripts to install the needed cross toolchains, which is very inconvenient; rustix has a large number of transitive dependents.

It made sense to use prebuilt archives for mips and power when we were already using prebuilt archives for other architectures anyway, but now that it's just mips and power, I think that changes. We've had multiple reports from users who want to vendor rustix in environments that disallow prebuilt archives. And the prebuilt archives are a bunch of extra work every time we need to update them. And in general, an open-source library in principle shouldn't have prebuilt archives in it. "We have a CI check that the binaries match the sources" isn't as easy to explain as "we have no binaries in the tree".

We'll keep linux_raw support for mips and power in the tree, and keep testing it in CI, and users who want to try it out can enable it with `RUSTFLAGS=--cfg=rustix_use_experimental_asm`, and my sense is it doesn't make sense to burden everyone else with prebuilt binaries in the tree.

**Comment by germag** [comment]
@sunfishcode Thanks!

**Comment by sunfishcode** [comment]
This is now done, and released in rustix 0.38.4. All the .a files are now gone!

**Comment by germag** [comment]
> This is now done, and released in rustix 0.38.4. All the .a files are now gone!

Thanks thanks!
