### ISSUE TITLE
Cannot set custom flags for fcntl_setfd

### ISSUE THREAD

**Issue by schwa** [bytecodealliance/rustix#761]
I need to use F_GLOBAL_NOCACHE on macOS in fcntl_setfd but there's only 1 flag defined for fdFlags.

Trying to force my own flag via rustix::io::FdFlags::from_bits(F_GLOBAL_NOCACHE).unwrap() fails.

Is there anything I can do to provide my own flag?

**Comment by sunfishcode** [comment]
You can do `FdFlags::from_bits_retain(F_GLOBAL_NOCACHE)`.

Filing a bug like this is also good, because then we can also add it to rustix :smile:.

**Comment by sunfishcode** [comment]
Actually, I was mistaken. It appears `F_GLOBAL_NOCACHE` is a `fcntl` opcode, and not a `F_SETFD` flag. So then, the answer is, rustix just needs to add a new function for it.

Do you know what the argument type of `F_GLOBAL_NOCACHE` is? That is, in `fcntl(fd, F_GLOBAL_NOCACHE, x)`, what's the `x`?

**Comment by schwa** [comment]
Thank you!
