### ISSUE TITLE
Add api to read passwd file

### ISSUE THREAD

**Issue by morr0ne** [bytecodealliance/rustix#791]
As the title say rustix would benefit from adding an equivalent to [getpwuid](https://linux.die.net/man/3/getpwuid). This functions simply returns the passwd entry for the corresponding uid. This is clearly a unix only api and as far as I can tell, all libc implementation currently obtain it by reading `/etc/passwd` line by line and returning the first entry with the corresponding uid or null if corresponding uid is found.

**Comment by sunfishcode** [comment]
`getpwuid` is an NSS function, so it also has the ability to `dlopen` in code that does arbitrary database queries, such as looking up users in LDAP or NIS or other things. The things it does wouldn't need access to any of rustix's internal machinery for making system calls; it could all be implemented as a separate crate on top of rustix's public API. My sense is that NSS functions are different enough from the rest of rustix that putting them in a separate crate would also be a logical organization.

Fwiw, mustang implements `getpwuid` for Linux [here](https://github.com/sunfishcode/mustang/blob/main/c-gull/src/nss.rs#L36). It parses the output of the `getent ` command, so that it gets NSS support without having to `dlopen` anything.

**Comment by morr0ne** [comment]
> `getpwuid` is an NSS function, so it also has the ability to `dlopen` in code that does arbitrary database queries, such as looking up users in LDAP or NIS or other things. The things it does wouldn't need access to any of rustix's internal machinery for making system calls; it could all be implemented as a separate crate on top of rustix's public API. My sense is that NSS functions are different enough from the rest of rustix that putting them in a separate crate would also be a logical organization.

Digging through the glibc source the way nss function is kinda strange. It really seem outside the scope of what a c library should do, other libc implementation do just read /etc/passwd. It's prob something way to old to be changed but looking into it further I do agree that it seem outside the scope of rustix. The better approach would probably be a crate that deals with any NSS function and use that when needed.

> Fwiw, mustang implements `getpwuid` for Linux [here](https://github.com/sunfishcode/mustang/blob/main/c-gull/src/nss.rs#L36). It parses the output of the `getent ` command, so that it gets NSS support without having to `dlopen` anything.

That seems like a rather strange approach, what happens if getent fails or doesn't exist? Does it even make sense to do it that way? I feel like the proper way would be to just depend on a crate (supposing it exist) that takes the place of the getent command.

**Comment by notgull** [comment]
Generally only things that map 1:1 with system calls should be exposed in `rustix`, at least according to my philosophy. Other things that require more implementation should be split into other crates, like [`rustix-openpty`](https://github.com/sunfishcode/rustix-openpty).

**Comment by sunfishcode** [comment]
> That seems like a rather strange approach, what happens if getent fails or doesn't exist? Does it even make sense to do it that way? I feel like the proper way would be to just depend on a crate (supposing it exist) that takes the place of the getent command.

It's worked in practice so far :smile:. And in some ways, running an external command is less strange than `mmap`ing some compiled C program into the process and letting it perform arbitrary file or network access from within the process, and make arbitrary assumptions about the process. But the other reason is that mustang doesn't have any `dlopen` support and it'd be a big project to implement it.

I should also mention, besides NIS/LDAP/etc., these days there's also systemd-sysusers.

We could have a separate crate if we wanted to, but wherever we put the implementation, it'd face the same considerations.

**Comment by morr0ne** [comment]
> It's worked in practice so far 😄. And in some ways, running an external command is less strange than `mmap`ing some compiled C program into the process and letting it perform arbitrary file or network access from within the process, and make arbitrary assumptions about the process. But the other reason is that mustang doesn't have any `dlopen` support and it'd be a big project to implement it.

Yeah, looking into it, it does seem like it is the best solution. It seems very unlikely that getent is not available and it will always be available in a gnu/linux system because its provided by glibc. The more I learn about libc and especially glibc, the more I think we put way to much os responsibilities on what is supposed to be a standard library. It looks like glibc essentially acts as the os. This probably isn't a surprise and just be not knowing enough about it but I can't help but feel this isn't the right approach.

> We could have a separate crate if we wanted to, but wherever we put the implementation, it'd face the same considerations.

I do feel like there's still might be a benefit in wrapping getent into it's own crate for a more idiomatic usage. Not sure how much it'll be used outside of rustix but it might make sense to separate.

**Comment by sunfishcode** [comment]
If you're interested in factoring out c-gull's nss code into a standalone crate, that would be fine with me. I think In any case, as discussed above, this wouldn't go in rustix here, so I'll close this issue.
