### ISSUE TITLE
Add feature flag to allow docs for runtime

### ISSUE THREAD

**Issue by morr0ne** [bytecodealliance/rustix#823]
As the title says, it would make working with rustix much easier. Currently using the runtime module is kinda tedious since there are no readily available docs. I does make sense to hide it by default but it would be nice to enable them when needed

**Comment by sunfishcode** [comment]
The module-level docs for the `runtime` module are not yet complete enough to say everything that users would need to be aware of to use these functions. At this time, it's still necessary to read all of their code, as the module-level docs say.

**Comment by sunfishcode** [comment]
Could you say more about what kinds of things you're using `rustix::runtime` for?

**Comment by morr0ne** [comment]
> The module-level docs for the `runtime` module are not yet complete enough to say everything that users would need to be aware of to use these functions. At this time, it's still necessary to read all of their code, as the module-level docs say.

I understand that but it makes it really hard to use them. Especially when dealing with no_std code where sometimes rust-analyzer likes to ignore type definitions and I need to look it up

> Could you say more about what kinds of things you're using `rustix::runtime` for?

I'm trying to use the `fork` and `execve` functions. Which on their own are already really hard to use safely, even more so when I can't easily access the docs.

I think a better solution would be to just make the docs available and feature gate everything behind an hidden `unstable_runtime` flag. What I mean by hidden is not defining the feature in the cargo manifest thus requiring the use of something like `RUSTFLAGS="--cfg unstable_runtime"` and making it impossible to use accidentally. This is what some major project like tokio opted to do and imo its the best solution since the module does not follow semver anyway

Finally I do think the name `runtime` is rather weird, while it does make sense for some function it does not for others, perhaps a better name would be `internals` or `sys`, even then, stuff like fork and execve feel like they should just belong to the normal crate api.

**Comment by sunfishcode** [comment]
Would this simple one-liner be sufficient?
```diff
diff --git a/src/lib.rs b/src/lib.rs
index 1f3a06ab..a23006f9 100644
--- a/src/lib.rs
+++ b/src/lib.rs
@@ -271,7 +271,7 @@ pub mod time;
 #[cfg(not(windows))]
 #[cfg(feature = "runtime")]
 #[cfg(linux_raw)]
-#[doc(hidden)]
+#[cfg_attr(not(document_experimental_runtime_api), doc(hidden))]
 #[cfg_attr(doc_cfg, doc(cfg(feature = "runtime")))]
 pub mod runtime;
```
If so, I think that change would be ok. Using `RUSTFLAGS="--cfg document_experimental_runtime_api"` means it isn't going to get accidentally enabled in Cargo.toml files, which seems good.

**Comment by sunfishcode** [comment]
I've now added the above patch, and confirmed that enabling the feature does enable the runtime docs.

**Comment by morr0ne** [comment]
Well that's exactly what I had in mind, thanks
