### ISSUE TITLE
How to get hostname?

### ISSUE THREAD

**Issue by flosse** [bytecodealliance/rustix#879]
Is there an equivalent to [`nix::unistd::gethostname`](https://docs.rs/nix/0.27.1/nix/unistd/fn.gethostname.html)?

**Comment by sunfishcode** [comment]
Yes, [`rustix::system::uname`](https://docs.rs/rustix/latest/rustix/system/fn.uname.html) and get the [`nodename()`](https://docs.rs/rustix/latest/rustix/system/struct.Uname.html#method.nodename).

**Comment by flosse** [comment]
@sunfishcode thanks for the fast reply! :pray:
