### ISSUE TITLE
Please support `CLOCK_BOOTTIME` in `clock_gettime` on Linux

### ISSUE THREAD

**Issue by joshtriplett** [bytecodealliance/rustix#905]
`rustix::time::ClockId` contains the clock IDs that always work, so that `clock_gettime` can't return an error. This enum already varies by platform, with some values only available on `cfg(linux_kernel)`, and some values only available on `not(cfg(apple))` for instance.

`CLOCK_BOOTTIME` is available on a variety of platforms, including Linux 2.6.39 and newer. Even Debian oldoldstable has a 4.19 kernel. RHEL 7 is ten years old and uses a 3.10 kernel.

If those aren't sufficient, then could you please:
- Add support under the `linux_4_11` feature flag, and
- Document the minimum supported kernel version for rustix?

Thank you!

**Comment by sunfishcode** [comment]
Thanks for the report! Rustix's current (and currently undocumented) policy has been to support Linux 2.6.32, but it does seem to make sense to change that, and document it. I filed https://github.com/bytecodealliance/rustix/issues/907 to propose this and collect feedback.

In the meantime, adding `Boottime` to `ClockId` under `linux_4_11` also sounds reasonable to me. I'll submit a PR when I get around to it, or I'd accept a PR if anyone wants to submit one sooner :smile:.

**Comment by sunfishcode** [comment]
#911 will add `Boottime` to `ClockkId` under `linux_4_11`.

**Comment by sunfishcode** [comment]
#911, adding `Boottime` to `ClockId` under `linux_4_11` is now released in 0.38.22.

I've also opened #927 to update the minimum supported Linux version to 3.2 and make `Boottime` available unconditionally.
