### ISSUE TITLE
`SendAncillaryBuffer::new(&[])` panics with out of range index (on FreeBSD, at least?)

### ISSUE THREAD

**Issue by ids1024** [bytecodealliance/rustix#914]
I noticed this in https://github.com/Smithay/wayland-rs/runs/18241136370. In this case, `send` perhaps would be more appropriate, but I think it should be possible to call `sendmsg` with an `iov` but not allocate any memory for ancillary messages when none are sent.

**Comment by ids1024** [comment]
Ah, I guess the inconsistency I've seen reproducing this is since it depends how the vec allocation happens to be aligned.

**Comment by sunfishcode** [comment]
It is possible to use `sendmsg` with an empty ancillary buffer, by using `SendAncillaryBuffer::default()` instead of `SendAncillaryBuffer::new(&mut [])`.

Is that good enough, do you think, such that we should just add more documentation/asserts to `new` pointing users to `default()` if they want an empty slice? Or, is it useful to be able to pass an empty slice into `new`, that we should have `new` handle it?

**Comment by ids1024** [comment]
Ah, I didn't see the `Default` implementation. That would be appropriate for this sort of thing. `__cmsg_space` also is now `const`, which it wasn't when I originally wrote this `sendmsg` call.

I guess it could document that `SendAncillaryBuffer::new` should only ever be called with a buffers allocated with a size from `cmsg_space!`, it may panic otherwise, and `default()` can be used for sending no messages? Not the best API though.

One reason to pass `&mut []` instead of use `default()` is if you have a branch using `&mut []` and another branch using something non-empty. But with the current API that doesn't seem to be possible, if you allocate a vec in one branch, since the `SendAncillaryBuffer` would outlive the vec.

Not sure what API would be better though, without forcing dynamic allocation.

**Comment by sunfishcode** [comment]
I submitted #915 with a draft of a possible fix here.

**Comment by sunfishcode** [comment]
This is now fixed in #915.

**Comment by sunfishcode** [comment]
This is now released in rustix 0.38.22.
